[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "ffmpeg", "tesseract"]

[phases.install]
cmds = ["python -m pip install --upgrade pip", "python -m pip install -r requirements.txt"]

[start]
cmd = "cd scripts/interface && python -m gunicorn --bind 0.0.0.0:$PORT --workers 2 --timeout 120 visual_browser:app"
